config/routes.rb
Rails.application.routes.draw do
  resources :list_items
  resources :carts
  resources :clothings
  root 'clothings#index'

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/clothing.rb
class Clothing < ApplicationRecord
    before_destroy :not_referenced_by_any_list_item
    belongs_to :user, optional: true
    has_many :list_items
    
    has_attached_file :image, styles: { medium: "300x300>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /image/
    

    # validates :brand, :description, :type, :price, presence: true 
    # validates :price, numericality: {only_integer: true}, length: {maximum: 7}

    BRAND = %w{Nike Gucci Adidas H&M Lungten JigmeBrand}

    private 
    
    def not_referenced_by_any_list_item
        unless list_items.empty?
            errors.add(:base, "List item is not present")
            throw :abort
        end
    end
    
end

app/controllers/clothings_controller.rb
class ClothingsController < ApplicationController
  before_action :set_clothing, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /clothings or /clothings.json
  def index
    @clothings = Clothing.all.order("created_at DESC")
  end

  # GET /clothings/1 or /clothings/1.json
  def show
  end

  # GET /clothings/new
  def new
    @clothing = current_user.clothings.build
  end

  # GET /clothings/1/edit
  def edit
  end

  # POST /clothings or /clothings.json
  def create
    @clothing = current_user.clothings.build(clothing_params)

    respond_to do |format|
      if @clothing.save
        format.html { redirect_to @clothing, notice: "Clothing was successfully created." }
        format.json { render :show, status: :created, location: @clothing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clothing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clothings/1 or /clothings/1.json
  def update
    respond_to do |format|
      if @clothing.update(clothing_params)
        format.html { redirect_to @clothing, notice: "Clothing was successfully updated." }
        format.json { render :show, status: :ok, location: @clothing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clothing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clothings/1 or /clothings/1.json
  def destroy
    @clothing.destroy
    respond_to do |format|
      format.html { redirect_to clothings_url, notice: "Clothing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clothing
      @clothing = Clothing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clothing_params
      params.require(:clothing).permit(:brand, :description, :type1, :price, :image, :title)
    end
end

app/helpers/clothings_helper.rb
module ClothingsHelper
    def clothing_author(clothing)
        user_signed_in? && current_user.id == clothing.user_id
    end
end

app/views/clothings/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">
    <%= simple_form_for @clothing, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

         <div class="field">
          <div class="control">
            <%= f.input :type, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Brand</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :brand, collection: Clothing::BRAND, prompt: "Select brand" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input clothings-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', clothings_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/clothings/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Clothing
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', clothing: @clothing %>
</div>

app/views/clothings/index.html.erb
<% content_for :header do%>
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title1">
        Browse the product to buy.
      </h1>
    </div>
  </div> 
</section>
<%end%>

<div class="clothingsContainer">
  <% @clothings.each do |cloth|%>
  <div class="clothing border-light">
    <%= link_to image_tag(cloth.image.url(:medium)), cloth %>
  </div>

  <div class="pa3">
      <h3 class="cloth_title"><%= link_to cloth.title, cloth %></h3>
      <p class="has-text-gray">Sold by <%= cloth.user.name %></p>
      <p class="price12"><%= number_to_currency(cloth.price) %></p>
      <% if clothing_author(cloth) %>
      <div class="btn-container">
         <%= link_to 'Edit', edit_clothing_path(cloth), class: "button is-small" %>
         <%= link_to 'Delete', cloth, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
         </div>
      <% end %>
        <%end%>
    </div>
</div>

app/views/clothings/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell Clothings
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', clothing: @clothing %>
</div>

app/views/clothings/show.html.erb
<% content_for :body_class, 'bg-light' %>
    <p id="notice"><%= notice %></p>
    <div class="show-image"></div>
    <%= image_tag(@clothing.image.url(:medium))%>
    <p>
        <strong>Brand:</strong>
        <%= @clothing.brand %>
    </p>

    <p>
        <strong>Description:</strong>
        <%= @clothing.description %>
    </p>

    <p>
        <strong>Type:</strong>
        <%= @clothing.type %>
    </p>

    <p>
        <strong>Price:</strong>
        <%= @clothing.price %>
    </p>

    <%if clothing_author(@clothing)%>
        <%= link_to 'Edit', edit_clothing_path(@clothing) %>
        |
    <%end%>
    <%= link_to 'Back', clothings_path %>
    <div class="column1">
        <div class="bg-white">
            <h4 class="title"><%= number_to_currency(@clothing.price) %></h4>
            <p class="text-sold">Sold by
                <%= @clothing.user.name %></p>
            <%= button_to 'Add to cart', list_items_path(clothing_id: @clothing), class:
            'button is-warning add-to-cart' %>
        </div>
    </div>
    <% content_for :body_class%>