config/routes.rb
Rails.application.routes.draw do
  resources :list_items
  resources :carts
  resources :clothings
  root 'clothings#index'

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :cart
  belongs_to :clothing

  def total_price
    if quantity.to_i >= 3 && quantity.to_i < 5
      (clothing.price.to_i * quantity.to_i) - 100
    elsif quantity.to_i >= 5 && quantity.to_i > 7
      (clothing.price.to_i * quantity.to_i) - 300
    elsif quantity.to_i >= 7
      (clothing.price.to_i * quantity.to_i) - 400
    elsif clothing.brand == "H&M"
      (clothing.price.to_i * quantity.to_i) - (0.1 * (clothing.price.to_i * quantity.to_i))
    else
      (clothing.price.to_i * quantity.to_i)
    end
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  include CurrentCart
  before_action :set_list_item, only: %i[ show edit update destroy ]
  before_action :set_cart, only: [:create]

  # GET /list_items or /list_items.json
  def index
    @list_items = ListItem.all
  end

  # GET /list_items/1 or /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items or /list_items.json
  def create
    clothing = Clothing.find(params[:clothing_id])
    @list_item = @cart.add_clothing(clothing)

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to @list_item.cart, notice: "Item added successfully to the cart." }
        format.json { render :show, status: :created, location: @list_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1 or /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to @list_item, notice: "List item was successfully updated." }
        format.json { render :show, status: :ok, location: @list_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1 or /list_items/1.json
  def destroy
    @cart = Cart.find(session[:cart_id])
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_path(@cart), notice: "List item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_item_params
      params.require(:list_item).permit(:clothing_id)
    end
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/list_items/_form.html.erb
<%= simple_form_for(@list_item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :clothing %>
    <%= f.association :cart %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/list_items/_list_item.html.erb
<div class="columns align-items-center">
  <div class="column is-1">
    <%= list_item.quantity %>
  </div>
  <div class="column is-2">
    <figure class="is-128x128 image">
      <%= image_tag(list_item.clothing.image.url(:thumb)) %>
    </figure>
  </div>
  <div class="column is-9">
    <strong><%= list_item.clothing.title %></strong>
    <div class="columns align-items-center">
      <div class="content column is-9">
        <%= truncate(list_item.clothing.description, length: 140) %>
      </div>
      <div class="column is-3 has-text-right">
        <strong class="f4"><%= number_to_currency(list_item.total_price) %></strong>
      </div>
    </div>
  </div>
</div>

<div class="has-text-right">
  <%= link_to 'Remove Item', list_item, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-small mb4" %>
</div>

<hr/ >

app/views/list_items/edit.html.erb
<h1>Editing List Item</h1>

<%= render 'form', list_item: @list_item %>

<%= link_to 'Show', @list_item %> |
<%= link_to 'Back', list_items_path %>

app/views/list_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List Items</h1>

<table>
  <thead>
    <tr>
      <th>Clothing</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list_items.each do |list_item| %>
      <tr>
        <td><%= list_item.clothing %></td>
        <td><%= list_item.cart_id %></td>
        <td><%= link_to 'Show', list_item %></td>
        <td><%= link_to 'Edit', edit_list_item_path(list_item) %></td>
        <td><%= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List Item', new_list_item_path %>

app/views/list_items/new.html.erb
<h1>New List Item</h1>

<%= render 'form', list_item: @list_item %>

<%= link_to 'Back', list_items_path %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clothing:</strong>
  <%= @list_item.clothing %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @list_item.cart_id %>
</p>

<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', list_items_path %>